
server:
  #context-path: /
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: utf-8
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
    port-header: X-Forwarded-Port
  port: 8099
#  session:
#    timeout: 1800
#security:
#  basic:
#    enabled: false
#swagger 配置

spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ifast?serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      WRITE_NUMBERS_AS_STRINGS: true
  #profiles:
    #active: dev
#  http:
#    multipart:
#      max-file-size: 30Mb
#      max-request-size: 30Mb
  #  redis:
  #    host: 127.0.0.1
  devtools:
    restart:
      enabled: false
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.test.firstspringbootproject.**.domain